### ISSUE TITLE
[BUG] git-vrc make breaking diff if there are meaningless space at the end of line

### ISSUE THREAD

**Issue by Sayamame-beans** [anatawa12/git-vrc#21]
Original Title: git-vrc sometimes make breaking diff of VRCSceneDescriptor prefab

> git-vrc、時々VRCSceneDescriptorの入ったprefabのYAMLを破壊する、謎のdiffを生み出します。。🤔💭
> https://twitter.com/kurone_kito/status/1739121877157855423

何らかの条件下で`layerCollisionArr`と`capacity`間の改行が消えている?
再現手順: 未確認
バージョン: 不明
Related?: #12

**Comment by kurone-kito** [comment]
まだ再現リポジトリなどの検証をしていませんが、
以下の手順で、かつ各手順ごとにコミットを挟むと再現しやすそうです。

1. git-vrc を含んだ `.gitattributes` を導入
2. Unity 2022 でワールドのプロジェクト作成
3. (本当に何もない)空のシーンの作成
4. VRCSceneDescriptor を含むゲームオブジェクト単体のプレハブを作成
5. 4 をシーンに結合する ⇦ ここで再現しやすそう

**Comment by anatawa12** [comment]
2022でunityyamlの仕様が変わったりしたのかな...調査します

**Comment by anatawa12** [comment]
@kurone-kito 壊れる該当のprefabファイルを提供していただけませんか？

**Comment by kurone-kito** [comment]
@anatawa12 こちらですね。。[VRCSceneDescriptor.prefab.zip](https://github.com/anatawa12/git-vrc/files/13763946/VRCSceneDescriptor.prefab.zip)

見ていて気づいたのですが、`layerCollisionArr` 値の末尾にスペースを含む場合、事象が発生するようです。
テキストエディタで故意に末尾スペースを削除すると、この事象は回避できます。

**Comment by anatawa12** [comment]
末尾にスペースで再現しました。ありがとうございます。

**Comment by anatawa12** [comment]
d821f2b7ac3b3de441be11f83ea626c18ec21fe6 で修正しましtあ
