### ISSUE TITLE
Unity Editorで生成されたライティングデータのバイナリファイル化に関する問題

### ISSUE THREAD

**Issue by tp-jp** [anatawa12/git-vrc#22]
## 問題点

Unity Editor で生成された LightBake データは `LightData.asset` ファイルに保存されます。このファイルはバイナリファイルですが、`.gitattributes` ファイルでテキストとして扱ってしまうと末尾に LF 文字が付与されてしまい、バイナリファイルとしては不正なファイルになってしまいます。

この問題を回避するには、`.gitattributes` ファイルで `LightData.asset` ファイルを個別にバイナリファイルとして指定する必要があります。

## 解決策

.gitattributes
```
*.asset filter=vrc eol=lf text
*.prefab filter=vrc eol=lf text
*.unity filter=vrc eol=lf text
LightingData.asset binary
```

上記のコードを追加することで、`LightData.asset` ファイルのみバイナリファイルとして扱われ、バージョン管理システムで正しく管理することができます。

**Comment by tp-jp** [comment]
> これはドキュメントで対処するしかなさそうですね。

そうですね。ドキュメントで対処していただく想定でした。

> またはtext指定をデフォルトattributeから除くかしてもいいかもしれないですね。

なるほど。確かにtext指定自体が不要ならattributeから除くのが良いかもしれません。

**Comment by tp-jp** [comment]
text指定を除くことで問題なく動作することを確認できました。
お手すきの際に README.md の修正をお願いいたします。
もし権限を頂ければこちらで `PullRequest` を作成いたします。

.gitattributes
```
*.asset filter=vrc
*.prefab filter=vrc
*.unity filter=vrc
```

**Comment by anatawa12** [comment]
明示的にautoにすることにしました。

Fixed in 601fe2881631542b263501b52ac01dad99dc6ede

なおPulRequestはpublic repositoryであるためどなたでも作成できます

**Comment by tp-jp** [comment]
ご対応ありがとうございます！
> なおPulRequestはpublic repositoryであるためどなたでも作成できます

すみません。public repositoryであることを失念していました..。
